### PR TITLE
Minor Server Changes

### PR DESCRIPTION
**Pull request by reznok**
The following changes are made:
- With @vesche's implementation of my multi client, the ClientConnection is no longer threaded and doesn't need to inherit from threading.Thread anymore and has been changed accordingly
- Sends kill command to client before closing connection

### CODE REVIEW

**Comment by vesche** [comment]
Hey sorry, can you git pull and recommit? I was doing a major overhaul on the crypto, but I won't be making any more major changes until maybe later tonight.

**Comment by reznok** [comment]
Man this is quite a merge conflict, but can do.

**Comment by reznok** [comment]
Done. There's an extra exciting feature, the ability to drop into an interactive shell on the target. 
Known Issues:
Doesn't support relative paths (ie: cd ..)

**Comment by reznok** [comment]
May want to adjust this PR to be to a certain commit instead of a branch...

Just added "Client periodic connection attempt"
In the client, the time between connection attempts can be adjusted. Clients will continually check for a connection, even after server is closed with "quit". To fully terminate a client, the server must send "kill".

**Comment by vesche** [comment]
Hey @reznok , I might look at doing a cherry-pick on some of these commits. I like the client retry on the server, and had it in the back of my mind to implement something like that. I'm not sure if the best way to implement it is to create the two loops like that inside the client...

Also, I like the addition to the server to gracefully kill all the clients on server exit.

I do really want to add an interactive shell, but I'm pretty sure there's a way to actually directly send an interactive `/bin/bash` or `cmd.exe` (based on platform) across the socket. I don't think it needs to be as involved as your implementation, but I'll look more into this.

I think I can do something like this for this PR... I'll look into more tomorrow when I'm sober.
```
git checkout -b reznok-master
git pull https://github.com/reznok/basicRAT/master.git reznok-master
git checkout reznok-master
git cherry-pick <commit-hash>
```

It's tough because I want some of these changes, but don't want others. Moving forward you probably should do PR from a different branch so I can merge and then cherry-pick from a seperate branch. Thanks for the collaboration!

**Comment by reznok** [comment]
A better implementation than the two loops would probably be a simple state machine for connected/not connected. I'll change to doing PRs for specific commits (pretty sure that's doable) instead of the entire branch, as this ended up getting messy fast.

**Comment by kodeine** [comment]
@reznok i tested ur fork, client does not reconnect if server is disconnected and then reconnected.

**Pull request closed without merging**
