### PR TITLE
code styling.. better condition flow, DRY..

### PR DESCRIPTION
**Pull request by Secur1tyC0d3r**
(sorry about my bad English..)

### CODE REVIEW

**Comment by vesche** [comment]
This will allow client command and server commands that require a client connection to execute without a client avaliable.

For example:
```
[?] basicRAT> pwd
Running pwd...
Error: 'NoneType' object has no attribute 'dhkey'
Error: 'NoneType' object has no attribute 'conn'
```

I appreciate the pull request, maybe we can look into changing this code block into something better. It is somewhat messy at the moment.

**Comment by Secur1tyC0d3r** [comment]
Thanks.. But are you sure about this.. i mean it won't do that.. it won't output this with my patch?

**Comment by deadPix3l** [comment]
I haven't run it, but just reading it, this won't work. Specifically server:220. If the ccid is 'bob', which is a valid client and the command is 'scan' which is a valid command not in that list, then it will say there is no client connected which is untrue.

**Comment by Secur1tyC0d3r** [comment]
Oh thanks @deadPix3l, i didn't release that.. but it's easy to fix by replacing `!=` by `==`?

**Comment by vesche** [comment]
@Secur1tyC0d3r That makes more sense now, thanks.

**Pull request merged**
