### PR TITLE
Server overhaul

### PR DESCRIPTION
**Pull request by reznok**
- Allows the connection of multiple clients
- All traffic is now base64 encoded before encrypted and transmitted
- Minor client changes to adapt to new server

Everything was written using the base socket library in an effort to reduce external dependencies. Use it just as before, an you will see new clients connect and populate the "clients" list. Use client <id> to switch to a new active client.
Not everything has been thoroughly tested, so may be prone to some unhandled exceptions.

### CODE REVIEW

**Comment by vesche** [comment]
reznok, thanks for the pull request! A lot of these changes are great, and I'm going to vet some of this code before merging or implementing. I'm not sure if I like some of the error handling on the client side. I'll dig into these purposed changes, and definitely give you credit if I use some of your code.

**Comment by vesche** [comment]
Follow on, I really appreciate this pull request... Unfortunately, I can't merge the code in this state. There are many errors and inconsistencies. Using the client command to connect to non-existing clients is allowed and causes odd errors. Running commands on the target causes odd feedback. There's no consistency with string formatting or error handling.

I definitely want to support connection from multiple clients, and this is going the right way. I may implement some of these ideas in the future, and like aforementioned I will give you credit if and when I do. Thanks again.

**Comment by reznok** [comment]
I see you added some parts of my version into yours. Glad to see it! 
I'm going to go ahead and close this PR and continue to work off of your version.
A quick note though, I see you took out the base64 encoding. This was due to a lot of string formatting issues (ex: run cat /etc/passwd). There's multiple ways of handling that, but I just wanted to let you know why I had it added.

**Comment by vesche** [comment]
reznok, thanks again your code really helped me implement the multi-client connection. It's pretty stable now with: good error checking, checking valid client ids, handling killing the client properly, and I restructured how the client sends commands.

**Pull request closed without merging**
